### ISSUE TITLE
BG number is red even though it's in-range

### ISSUE THREAD

**Issue by cascer1** [leogandmars/nightscout-chrome#8]
![image](https://user-images.githubusercontent.com/7243299/50073773-fb783180-01d9-11e9-82b3-aa98b663d5fb.png)

In Nightscout I configured my range to be 4-8 mmol/L. However, the plugin reports a BG of 4.3 as low.

**Comment by leogandmars** [comment]
this is likely due to the fact that it doesn't currently pull nightscout alarm values, but since I recently added the pulling of MMOL/MGDL from the nightscout profile this should be pretty easy to implement. A temporary solution would be to manually set the alarm values in the settings page. 

I will update when I make progress on this.

**Comment by leogandmars** [comment]
Closed because of similarity to https://github.com/leogandmars/nightscout-chrome/issues/2
Please see that issue for updates
